ITUI/ITUI-war/src/java/managedBean/MotsCleMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedBean;

import entity.Motscle;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import managedBean.util.Util;
import session.MotsCleManager;

/**
 *
 * @author pro
 */
@Named(value = "motsCle")
@ViewScoped

public class MotsCleMBean implements Serializable{
    
    @EJB
    private MotsCleManager motsCleManager;
    private final Motscle m = new Motscle();
    private Motscle mc;
    private Long id;

    public Motscle getMc() {
        return mc;
    }
    public Motscle get_motsCle() {
        return m;
    }
    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    
    public List<Motscle> getAllMotsCle() {
        return motsCleManager.getAllMotsCle();
    }

    public String supprimerMotsCle(Motscle motsCle) {
        motsCleManager.supprimerMotsCle(motsCle);
        Util.addFlashInfoMessage("Mots Cle " + motsCle.getContenu() + " supprimé");
        return "liste?faces-redirect=true";
    }
    
    public String getMotsCleId(Motscle motsCle) {
        mc = motsCleManager.getMotsCle(motsCle.getId());
        return "modif?faces-redirect=true";
    }
    
    public String enregistrer() {
        motsCleManager.update(mc);
        return "liste?faces-redirect=true";
    }
    
    public String creerMotsCle() {
        motsCleManager.creerMotsCle(m);
        return "liste?faces-redirect=true";
    }
}

ITUI/ITUI-war/web/page/admin/motscle/ajout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    
    <h:head>
        <title>Ajout</title>
    </h:head>
    <h:body>
       <ui:composition template="/WEB-INF/template/template.xhtml">
            <ui:param name="titre" value="Créer un mots cle" />
            <ui:define name="content">
               
                <f:view>
                    <h:form>
                        <h1><h:outputText value="Ajout/Modif"/></h1>
                        <h:panelGrid columns="3">
                            <h:outputLabel value="Contenu:" for="contenu" />
                            <h:inputText id="contenu" value="#{motsCle._motsCle.contenu}" 
                                         title="Contenu" 
                                         required="true"/>
                            <h:message for="contenu"/>
                        </h:panelGrid>
                        <h:panelGrid columns="3">
                            <h:outputLabel value="Etat:" for="etat" />
                            <h:inputText id="etat" value="#{motsCle._motsCle.etat}" 
                                         title="Etat">
                                <f:convertNumber integerOnly="true" type="number" />
                            </h:inputText>
                            <h:message for="etat"/>
                        </h:panelGrid>
                        <h:commandButton action='#{motsCle.creerMotsCle()}'
                                         value="Créer le mots cle"/>
                    </h:form>
                </f:view>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

ITUI/ITUI-war/web/page/admin/motscle/liste.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>ITUI</title>
    </h:head>
    <h:body>
        <ui:composition template="/WEB-INF/template/template.xhtml">
            <ui:param name="titre" value="Liste des confidentialit&eacute;s"/>

            <ui:define name="content">
                <f:view>
                    <h:form>
                        <p:dataTable value="#{motsCle.allMotsCle}" var="item"
                                     tableStyle="width:auto" 
                                     paginator="true" rows="10"
                                     rowsPerPageTemplate="2,5,10,20">
                            <p:column width="40">
                                <f:facet name="header">
                                    <h:outputText value="Id"/>
                                </f:facet>
                                <h:outputText value="#{item.id}"/>
                            </p:column>
                            <p:column width="300" filterBy="#{item.contenu}" sortBy="#{item.contenu}">
                                <f:facet name="header">
                                    <h:outputText value="Contenu"/>
                                </f:facet>
                                <h:outputText value="#{item.contenu}"/>
                            </p:column>
                            <p:column width="300" filterBy="#{item.etat}" sortBy="#{item.etat}">
                                <f:facet name="header">
                                    <h:outputText value="Etat"/>
                                </f:facet>
                                <h:outputText value="#{item.etat}"/>
                            </p:column>
                            <p:column width="10">
                                <f:facet name="header">
                                  <h:outputText value="Opérations"/>
                                </f:facet>
                                <p:commandLink action="#{motsCle.supprimerMotsCle(item)}">
                                    <p:confirm 
                                        header="Confirmation"
                                        message="Voulez-vous vraiment supprimer?" />
                                    <h:graphicImage name="images/del.png"/>
                                </p:commandLink>
                                <br/>
                                <h:commandLink action="#{motsCle.getMotsCleId(item)}" value="Modifier">
                                </h:commandLink>
                                
                            </p:column>
                        </p:dataTable>
                        <p:confirmDialog global="true">
                          <p:commandButton value="Oui" type="button" 
                                           styleClass="ui-confirmdialog-yes"/>
                          <p:commandButton value="Non" type="button" 
                                           styleClass="ui-confirmdialog-no"/>
                        </p:confirmDialog>
                    </h:form>
                </f:view>
            </ui:define>
        </ui:composition>
    </h:body>
</html>