ITUI/ITUI-war/src/java/managedBean/NotificationMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedBean;

import entity.Confidentialite;
import entity.Notification;
import entity.Question;
import entity.Utilisateur;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import session.ConfidentialiteManager;
import managedBean.util.Util;
import session.NotificationManager;
import session.QuestionManager;
import session.UtilisateurManager;

/**
 *
 * @author pro
 */
@Named(value = "notification")
@ViewScoped

public class NotificationMBean implements Serializable{

    @EJB
    private NotificationManager notificationManager;
    
    @EJB
    private QuestionManager questionManager;
    
    private final Notification n = new Notification();
    private Notification notif;
    private Long id;

    public Notification getNotif() {
        return notif;
    }
    public Notification get_notification() {
        return n;
    }
    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    
    public List<Notification> getAllNotification() {
        return notificationManager.getAllNotification();
    }
    
    public List<Question> getAllQuestion() {
      return questionManager.getAllQuestion();
    }

    public String supprimerNotification(Notification notification) {
        notificationManager.supprimerNotification(notification);
        Util.addFlashInfoMessage("Notification " + notification.getId() + " supprimé");
        return "liste?faces-redirect=true";
    }
    
    public String enregistrer() {
        notificationManager.update(notif);
        return "liste?faces-redirect=true";
    }
    
    public String creerNotification() {
        notificationManager.creerNotification(n);
        return "liste?faces-redirect=true";
    }
    
}

ITUI/ITUI-war/src/java/managedBean/QuestionMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedBean;

import entity.Confidentialite;
import entity.Question;
import entity.Utilisateur;
import java.io.Serializable;
import java.sql.Date;
import java.util.List;
import javax.ejb.EJB;
import javax.ejb.Stateless;
import javax.ejb.LocalBean;
import javax.faces.convert.Converter;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import managedBean.util.Util;
import session.ConfidentialiteManager;
import session.QuestionManager;
import session.UtilisateurManager;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;



/**
 *
 * @author pro
 */

@Named(value = "question")
@ViewScoped

public class QuestionMBean implements Serializable{
    
    @EJB
    private QuestionManager questionManager;
    
    @EJB
    private UtilisateurManager utilisateurManager;
    
    @EJB
    private ConfidentialiteManager confidentialiteManager;
    
    private final Question q = new Question();
    
    public Question get_question() {
        return q;
    }
    
    public List<Question> getAllQuestion() {
        return questionManager.getAllQuestion();
    }
    
    public List<Utilisateur> getAllUtilisateur() {
      return utilisateurManager.getAllUtilisateur();
    }
    
    public List<Confidentialite> getAllConfidentialite() {
      return confidentialiteManager.getAllConfidentialite();
    }
    
    public String supprimerQuestion(Question question) {
        questionManager.supprimerQuestion(question);
        Util.addFlashInfoMessage("Question " + question.getLibelle() + " supprimé");
        return "liste?faces-redirect=true";
    }
    
    public String creerQuestion() {
        questionManager.creerQuestion(q);
        return "liste?faces-redirect=true";
    }
   
}

ITUI/ITUI-war/web/page/admin/notification/ajout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    
    <h:head>
        <title>Ajout</title>
    </h:head>
    <h:body>
       <ui:composition template="/WEB-INF/template/template.xhtml">
            <ui:param name="titre" value="Créer un mots cle" />
            <ui:define name="content">
               
                <f:view>
                    <h:form>
                        <h1><h:outputText value="Ajout/Modif"/></h1>
                        
                        <h:panelGrid columns="3">
                            <h:outputLabel value="Question" for="question" />
                            <h:selectOneMenu id="utilisateur" value="#{notification._notification.question}"   
                                            title="question" required="true" 
                                            converter="#{QuestionConverter}">   
                               <f:selectItems value="#{notification.allQuestion}"  
                                              var="item"   
                                              itemLabel="#{item.libelle}" itemValue="#{item}" /> 
                           </h:selectOneMenu>
                        </h:panelGrid>
                        
                        <h:panelGrid columns="3">
                            <h:outputLabel value="Etat:" for="etat" />
                            <h:inputText id="etat" value="#{notification._notification.etat}" 
                                         title="Etat">
                                <f:convertNumber integerOnly="true" type="number" />
                            </h:inputText>
                            <h:message for="etat"/>
                        </h:panelGrid>
                        <h:commandButton action='#{notification.creerNotification()}'
                                         value="Créer la notification"/>
                    </h:form>
                </f:view>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

ITUI/ITUI-war/web/page/admin/notification/liste.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>ITUI</title>
    </h:head>
    <h:body>
        <ui:composition template="/WEB-INF/template/template.xhtml">
            <ui:param name="titre" value="Liste des notifications"/>

            <ui:define name="content">
                <f:view>
                    <h:form>
                        <p:dataTable value="#{notification.allNotification}" var="item"
                                     tableStyle="width:auto" 
                                     paginator="true" rows="10"
                                     rowsPerPageTemplate="2,5,10,20">
                            <p:column width="40">
                                <f:facet name="header">
                                    <h:outputText value="Id"/>
                                </f:facet>
                                <h:outputText value="#{item.id}"/>
                            </p:column>
                            <p:column width="300" filterBy="#{item.question}" sortBy="#{item.question}">
                                <f:facet name="header">
                                    <h:outputText value="Question"/>
                                </f:facet>
                                <h:outputText value="#{item.question.libelle}"/>
                            </p:column>
                            <p:column width="300" filterBy="#{item.etat}" sortBy="#{item.etat}">
                                <f:facet name="header">
                                    <h:outputText value="Etat"/>
                                </f:facet>
                                <h:outputText value="#{item.etat}"/>
                            </p:column>
                            <p:column width="10">
                                <f:facet name="header">
                                  <h:outputText value="Opérations"/>
                                </f:facet>
                                <p:commandLink action="#{notification.supprimerNotification(item)}">
                                    <p:confirm 
                                        header="Confirmation"
                                        message="Voulez-vous vraiment supprimer?" />
                                    <h:graphicImage name="images/del.png"/>
                                </p:commandLink>
                                <br/>
                            </p:column>
                        </p:dataTable>
                        <p:confirmDialog global="true">
                          <p:commandButton value="Oui" type="button" 
                                           styleClass="ui-confirmdialog-yes"/>
                          <p:commandButton value="Non" type="button" 
                                           styleClass="ui-confirmdialog-no"/>
                        </p:confirmDialog>
                    </h:form>
                </f:view>
            </ui:define>
        </ui:composition>
    </h:body>
</html>