ITUI/ITUI-war/src/java/managedBean/ReponseMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedBean;

import entity.Confidentialite;
import entity.Question;
import entity.Reponse;
import entity.Utilisateur;
import java.io.Serializable;
import java.sql.Date;
import java.util.List;
import javax.ejb.EJB;
import javax.ejb.Stateless;
import javax.ejb.LocalBean;
import javax.faces.convert.Converter;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import managedBean.util.Util;
import session.ConfidentialiteManager;
import session.QuestionManager;
import session.UtilisateurManager;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import session.ReponseManager;



/**
 *
 * @author pro
 */

@Named(value = "reponse")
@ViewScoped

public class ReponseMBean implements Serializable{
    
    @EJB
    private ReponseManager reponseManager;
    
    @EJB
    private UtilisateurManager utilisateurManager;
    
    @EJB
    private ConfidentialiteManager confidentialiteManager;
    
    private final Reponse r = new Reponse();
    
    public Reponse get_reponse() {
        return r;
    }
    
    public List<Reponse> getAllReponse() {
        return reponseManager.getAllReponse();
    }
    
    public List<Utilisateur> getAllUtilisateur() {
      return utilisateurManager.getAllUtilisateur();
    }
    
    public List<Confidentialite> getAllConfidentialite() {
      return confidentialiteManager.getAllConfidentialite();
    }
    
    public String supprimerReponse(Reponse reponse) {
        reponseManager.supprimerReponse(reponse);
        Util.addFlashInfoMessage("Reponse " + reponse.getLibelle() + " supprimé");
        return "liste?faces-redirect=true";
    }
    
    public String creerReponse() {
        reponseManager.creerReponse(r);
        return "liste?faces-redirect=true";
    }
   
}

ITUI/ITUI-war/src/java/managedBean/RoleMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedBean;

import entity.Role;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import managedBean.util.Util;
import session.RoleManager;

/**
 *
 * @author pro
 */
@Named(value = "role")
@ViewScoped

public class RoleMBean implements Serializable{

    @EJB
    private RoleManager roleManager;
    private final Role r = new Role();
    private Role role;
    private Long id;
    
    public Role getRole() {
        return role;
    }
    public Role get_role() {
        return r;
    }
    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    
    public List<Role> getAllRole() {
        return roleManager.getAllRole();
    }

    public String supprimerRole(Role role) {
        roleManager.supprimerRole(role);
        Util.addFlashInfoMessage("Role " + role.getLibelle() + " supprimé");
        return "liste?faces-redirect=true";
    }
    
    public String getRoleId(Role role) {
        role = roleManager.getRole(role.getId());
        return "modif?faces-redirect=true";
    }
    
    public String enregistrer() {
        roleManager.update(role);
        return "liste?faces-redirect=true";
    }
    
    public String creerRole() {
        roleManager.creerRole(r);
        return "liste?faces-redirect=true";
    }
}

ITUI/ITUI-war/src/java/managedBean/UtilisateurRoleMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedBean;

import entity.*;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import managedBean.util.Util;
import session.*;
import session.RoleManager;
import session.UtilisateurManager;
import session.UtilisateurRoleManager;

/**
 *
 * @author pro
 */
@Named(value = "utilisateurrole")
@ViewScoped

public class UtilisateurRoleMBean implements Serializable{

    @EJB
    private UtilisateurRoleManager utilisateurRoleManager;
    @EJB
    private UtilisateurManager utilisateurManager;
    @EJB
    private RoleManager roleManager;
    
    private final Roleutilisateur ur = new Roleutilisateur();
    private Roleutilisateur userR;
    private Long id;

    public Roleutilisateur getUserR() {
        return userR;
    }
    public Roleutilisateur get_utilisateurRole() {
        return ur;
    }
    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    
    public List<Roleutilisateur> getAllUtilisateurRole() {
        return utilisateurRoleManager.getAllUtilisateurRole();
    }
    
    public List<Utilisateur> getAllUtilisateur() {
        return utilisateurManager.getAllUtilisateur();
    }
    
    public List<Role> getAllRole() {
        return roleManager.getAllRole();
    }

    public String supprimerUtilisateurRole(Roleutilisateur utilisateurRole) {
        utilisateurRoleManager.supprimerUtilisateurRole(utilisateurRole);
        Util.addFlashInfoMessage("Utilisateur role " + utilisateurRole.getId() + " supprimé");
        return "liste?faces-redirect=true";
    }
    
    public String enregistrer() {
        utilisateurRoleManager.update(userR);
        return "liste?faces-redirect=true";
    }
    
    public String creerUtilisateurRole() {
        ur.setMail(ur.getUtilisateur().getMail());
       utilisateurRoleManager.creerUtilisateurRole(ur);
       return "liste?faces-redirect=true";
    }
    
}

ITUI/ITUI-war/web/page/admin/utilisateurrole/ajout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    
    <h:head>
        <title>Ajout</title>
    </h:head>
    <h:body>
       <ui:composition template="/WEB-INF/template/template.xhtml">
            <ui:param name="titre" value="Créer un utilisateur role" />
            <ui:define name="content">
               
                <f:view>
                    <h:form>
                        <h1><h:outputText value="Ajout/Modif"/></h1>
                        <h:panelGrid columns="3">
                            <h:outputLabel value="Utilisateur" for="utilisateur" />
                            <h:selectOneMenu id="utilisateur" value="#{utilisateurrole._utilisateurRole.utilisateur}"   
                                            title="utilisateur" required="true" 
                                            converter="#{UtilisateurConverter}">   
                               <f:selectItems value="#{utilisateur.allUtilisateur}"  
                                              var="item"   
                                              itemLabel="#{item.nom}" itemValue="#{item}" /> 
                           </h:selectOneMenu>
                        </h:panelGrid>
                        <h:panelGrid columns="3">
                            <h:outputLabel value="Role" for="role" />
                            <h:selectOneMenu id="role" value="#{utilisateurrole._utilisateurRole.role}"   
                                            title="utilisateur" required="true" 
                                            converter="#{RoleConverter}">   
                               <f:selectItems value="#{utilisateur.allRole}"  
                                              var="item"   
                                              itemLabel="#{item.libelle}" itemValue="#{item}" /> 
                           </h:selectOneMenu>
                        </h:panelGrid>
                        <h:commandButton action='#{utilisateurrole.creerUtilisateurRole()}'
                                         value="Créer"/>
                    </h:form>
                </f:view>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

ITUI/ITUI-war/web/page/admin/utilisateurrole/liste.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>ITUI</title>
    </h:head>
    <h:body>
        <ui:composition template="/WEB-INF/template/template.xhtml">
            <ui:param name="titre" value="Liste des roles utilisateur"/>

            <ui:define name="content">
                <f:view>
                    <h:form>
                        <p:dataTable value="#{utilisateurrole.allUtilisateurRole}" var="item"
                                     tableStyle="width:auto" 
                                     paginator="true" rows="10"
                                     rowsPerPageTemplate="2,5,10,20">
                            <p:column width="40">
                                <f:facet name="header">
                                    <h:outputText value="Id"/>
                                </f:facet>
                                <h:outputText value="#{item.id}"/>
                            </p:column>
                            <p:column width="300" filterBy="#{item.utilisateur}" sortBy="#{item.utilisateur}">
                                <f:facet name="header">
                                    <h:outputText value="Utilisateur"/>
                                </f:facet>
                                <h:outputText value="#{item.utilisateur.nom}"/>
                            </p:column>
                            <p:column width="300" filterBy="#{item.role}" sortBy="#{item.role}">
                                <f:facet name="header">
                                    <h:outputText value="Role"/>
                                </f:facet>
                                <h:outputText value="#{item.role.libelle}"/>
                            </p:column>
                            <p:column width="10">
                                <f:facet name="header">
                                  <h:outputText value="Opérations"/>
                                </f:facet>
                                <p:commandLink action="#{utilisateurrole.supprimerUtilisateurRole(item)}">
                                    <p:confirm 
                                        header="Confirmation"
                                        message="Voulez-vous vraiment supprimer?" />
                                    <h:graphicImage name="images/del.png"/>
                                </p:commandLink>
                                <br/>
                            </p:column>
                        </p:dataTable>
                        <p:confirmDialog global="true">
                          <p:commandButton value="Oui" type="button" 
                                           styleClass="ui-confirmdialog-yes"/>
                          <p:commandButton value="Non" type="button" 
                                           styleClass="ui-confirmdialog-no"/>
                        </p:confirmDialog>
                    </h:form>
                </f:view>
            </ui:define>
        </ui:composition>
    </h:body>
</html>