ITUI/ITUI-war/src/java/managedBean/QuestionMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedBean;

import entity.Confidentialite;
import entity.Question;
import entity.Utilisateur;
import java.io.Serializable;
import java.sql.Date;
import java.util.List;
import javax.ejb.EJB;
import javax.ejb.Stateless;
import javax.ejb.LocalBean;
import javax.faces.convert.Converter;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import managedBean.util.Util;
import session.ConfidentialiteManager;
import session.QuestionManager;
import session.UtilisateurManager;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;



/**
 *
 * @author pro
 */

@Named(value = "question")
@ViewScoped

public class QuestionMBean implements Serializable{
    
    @EJB
    private QuestionManager questionManager;
    
    @EJB
    private UtilisateurManager utilisateurManager;
    
    @EJB
    private ConfidentialiteManager confidentialiteManager;
    
    private final Question q = new Question();
    
    public Question get_question() {
        return q;
    }
    
    public List<Question> getAllQuestion() {
        return questionManager.getAllQuestion();
    }
    
    public List<Utilisateur> getAllUtilisateur() {
      return utilisateurManager.getAllUtilisateur();
    }
    
    public List<Confidentialite> getAllConfidentialite() {
      return confidentialiteManager.getAllConfidentialite();
    }
    
    public String supprimerQuestion(Question question) {
        questionManager.supprimerQuestion(question);
        Util.addFlashInfoMessage("Question " + question.getLibelle() + " supprimé");
        return "liste?faces-redirect=true";
    }
    
    public String creerQuestion() {
        questionManager.creerQuestion(q);
        return "liste?faces-redirect=true";
    }
   
}

ITUI/ITUI-war/src/java/managedBean/ReponseMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedBean;

import entity.Confidentialite;
import entity.Question;
import entity.Reponse;
import entity.Utilisateur;
import java.io.Serializable;
import java.sql.Date;
import java.util.List;
import javax.ejb.EJB;
import javax.ejb.Stateless;
import javax.ejb.LocalBean;
import javax.faces.convert.Converter;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import managedBean.util.Util;
import session.ConfidentialiteManager;
import session.QuestionManager;
import session.UtilisateurManager;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import session.ReponseManager;



/**
 *
 * @author pro
 */

@Named(value = "reponse")
@ViewScoped

public class ReponseMBean implements Serializable{
    
    @EJB
    private ReponseManager reponseManager;
    
    @EJB
    private UtilisateurManager utilisateurManager;
    
    @EJB
    private ConfidentialiteManager confidentialiteManager;
    
    private final Reponse r = new Reponse();
    
    public Reponse get_reponse() {
        return r;
    }
    
    public List<Reponse> getAllReponse() {
        return reponseManager.getAllReponse();
    }
    
    public List<Utilisateur> getAllUtilisateur() {
      return utilisateurManager.getAllUtilisateur();
    }
    
    public List<Confidentialite> getAllConfidentialite() {
      return confidentialiteManager.getAllConfidentialite();
    }
    
    public String supprimerReponse(Reponse reponse) {
        reponseManager.supprimerReponse(reponse);
        Util.addFlashInfoMessage("Reponse " + reponse.getLibelle() + " supprimé");
        return "liste?faces-redirect=true";
    }
    
    public String creerReponse() {
        reponseManager.creerReponse(r);
        return "liste?faces-redirect=true";
    }
   
}

ITUI/ITUI-war/src/java/managedbean/QuestionBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedbean;

import entity.*;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import javax.servlet.http.HttpServletRequest;
import session.ConfidentialiteManager;
import session.QuestionManager;
import session.UtilisateurManager;
/**
 *
 * @author Nante-PC
 */
@Named(value = "questionBean")
@ViewScoped
public class QuestionBean implements Serializable {
    private List < Question > QuestionList;
    private int id;
    private String msg;
    private Question q;
    private String categorie;
    private String libelle;

    @EJB
    private QuestionManager questionManager;
    private UtilisateurManager userManager;
    private ConfidentialiteManager confManager;
    
    public QuestionBean() {}
    public List <Question> getQuestion() {
        QuestionList = questionManager.getAllQuestion();
        return QuestionList;
    }

    public void Supprimer(Long id) {
        Question q = questionManager.getQuestion(id);
        q.setEtat(1);
        questionManager.update(q);
    }

    public String Voir(Long id) {
        return "detailsQuestion?faces-redirect=true&id="+id;
    }

    public String voirReponse(Long id) {
        return "listeReponse?faces-redirect=true&id=" + id;
    }
    public Question detailsQuestion() {
        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        this.id = Integer.parseInt(request.getParameter("id"));
        q = questionManager.getQuestion(Long.valueOf(id));
        return q;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }
    public String getMsg() {
        return msg;
    }
    
    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }
    public String getCategorie() {
        return categorie;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public String getLibelle() {
        return libelle;
    }
    
    public void Modifier(Long id) {
        Question question = questionManager.getQuestion(id);
        question.setCategorie(this.q.getCategorie());
        question.setLibelle(this.q.getLibelle());
    }
    
    public void ajouter(){
        //Date date = new Date();
        //Calendar cal = Calendar.getInstance();
        //String heure = cal.get(Calendar.HOUR_OF_DAY)+"h "+cal.get(Calendar.MINUTE)+"m et "+cal.get(Calendar.SECOND)+"s";
        //Long id = questionManager.nbQuestion();
        //Confidentialite conf = confManager.getConfidentialite(1);
    }
}

ITUI/ITUI-war/web/page/admin/question/ajout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    
    <h:head>
        <title>Ajout</title>
    </h:head>
    <h:body>
       <ui:composition template="/WEB-INF/template/template.xhtml">
          
            <ui:param name="titre" value="Créer un question" />
            <ui:define name="content">
                <f:view>
                    <h:form>
                        <h1><h:outputText value="Ajout/Modif"/></h1>
                        <h:panelGrid columns="3">
                            <h:outputLabel value="Libelle:" for="libelle" />
                            <h:inputText id="libelle" value="#{question._question.libelle}" 
                                         title="Libelle" 
                                         required="true"/>
                            <h:message for="libelle"/>
                        </h:panelGrid>
                        <h:panelGrid columns="3">
                            <h:outputLabel value="Categorie:" for="categorie" />
                            <h:inputText id="categorie" value="#{question._question.categorie}" 
                                         title="Categorie" 
                                         required="true"/>
                            <h:message for="categorie"/>
                        </h:panelGrid>
                        <h:panelGrid columns="3">
                            <h:outputLabel value="Date" for="daty" />
                            <h:inputText id = "daty" value = "#{question._question.daty}"
                                label = "Date" >
                                <f:convertDateTime pattern = "yyyy-mm-dd" />
                            </h:inputText>
                            <h:message for="daty"/>
                        </h:panelGrid>
                        <h:panelGrid columns="3">
                            <h:outputLabel value="Heure" for="heure" />
                            <h:inputText id="heure" value="#{question._question.heure}" 
                                         title="Heure" 
                                         required="true"/>
                            <h:message for="heure"/>
                        </h:panelGrid>
                        <h:panelGrid columns="3">
                            <h:outputLabel value="Titre" for="titre" />
                            <h:inputText id="titre" value="#{question._question.titre}" 
                                         title="Titre" 
                                         required="true"/>
                            <h:message for="titre"/>
                        </h:panelGrid>
                        <h:panelGrid columns="3">
                            <h:outputLabel value="Code" for="code" />
                            <h:inputText id="code" value="#{question._question.code}" 
                                         title="Code" 
                                         required="true"/>
                            <h:message for="code"/>
                        </h:panelGrid>
                        
                        <h:panelGrid columns="3">
                            <h:outputLabel value="Etat" for="etat" />
                            <h:inputText id="etat" value="#{question._question.etat}" 
                                         title="Etat" >
                                <f:convertNumber integerOnly="true" type="number" />
                            </h:inputText>
                            <h:message for="etat"/>
                        </h:panelGrid>
                        
                        <h:panelGrid columns="3">
                            <h:outputLabel value="Utilisateur" for="utilisateur" />
                            <h:selectOneMenu id="utilisateur" value="#{question._question.utilisateur}"   
                                            title="utilisateur" required="true" 
                                            converter="#{UtilisateurConverter}">   
                               <f:selectItems value="#{question.allUtilisateur}"  
                                              var="item"   
                                              itemLabel="#{item.nom}" itemValue="#{item}" /> 
                           </h:selectOneMenu>
                        </h:panelGrid>
                        
                        <h:panelGrid columns="3">
                            <h:outputLabel value="Confidentialite" for="confidentialite" />
                            <h:selectOneMenu id="confidentialite" value="#{question._question.confidentialite}"   
                                            title="confidentialite" required="true" 
                                            converter="#{ConfidentialiteConverter}">   
                               <f:selectItems value="#{question.allConfidentialite}"  
                                              var="item"   
                                              itemLabel="#{item.libelle}" itemValue="#{item}" /> 
                           </h:selectOneMenu>
                        </h:panelGrid>
                        
                        <h:commandButton action='#{question.creerQuestion()}'
                                         value="Créer la question"/>
                    </h:form>
                </f:view>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

ITUI/ITUI-war/web/page/admin/question/liste.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>ITUI</title>
    </h:head>
    <h:body>
        <ui:composition template="/WEB-INF/template/template.xhtml">
            <ui:param name="titre" value="Liste des questions"/>

            <ui:define name="content">
                <f:view>
                    <h:form>
                        <p:dataTable value="#{question.allQuestion}" var="item"
                                     tableStyle="width:auto" 
                                     paginator="true" rows="10"
                                     rowsPerPageTemplate="2,5,10,20">
                            <p:column width="40">
                                <f:facet name="header">
                                    <h:outputText value="Id"/>
                                </f:facet>
                                <h:outputText value="#{item.id}"/>
                            </p:column>
                            <p:column width="300" filterBy="#{item.libelle}" sortBy="#{item.libelle}">
                                <f:facet name="header">
                                    <h:outputText value="Libelle"/>
                                </f:facet>
                                <h:outputText value="#{item.libelle}"/>
                            </p:column>
                            <p:column width="300" filterBy="#{item.categorie}" sortBy="#{item.categorie}">
                                <f:facet name="header">
                                    <h:outputText value="Categorie"/>
                                </f:facet>
                                <h:outputText value="#{item.categorie}"/>
                            </p:column>
                            <p:column width="300" filterBy="#{item.daty}" sortBy="#{item.daty}">
                                <f:facet name="header">
                                    <h:outputText value="Date"/>
                                </f:facet>
                                <h:outputText value="#{item.daty}"/>
                            </p:column>
                            <p:column width="300" filterBy="#{item.heure}" sortBy="#{item.heure}">
                                <f:facet name="header">
                                    <h:outputText value="Heure"/>
                                </f:facet>
                                <h:outputText value="#{item.heure}"/>
                            </p:column>
                            <p:column width="300" filterBy="#{item.titre}" sortBy="#{item.titre}">
                                <f:facet name="header">
                                    <h:outputText value="Titre"/>
                                </f:facet>
                                <h:outputText value="#{item.titre}"/>
                            </p:column>
                            <p:column width="300" filterBy="#{item.code}" sortBy="#{item.code}">
                                <f:facet name="header">
                                    <h:outputText value="Code"/>
                                </f:facet>
                                <h:outputText value="#{item.code}"/>
                            </p:column>
                            <p:column width="300" filterBy="#{item.etat}" sortBy="#{item.etat}">
                                <f:facet name="header">
                                    <h:outputText value="Etat"/>
                                </f:facet>
                                <h:outputText value="#{item.etat}"/>
                            </p:column>
                            <p:column width="300" filterBy="#{item.utilisateur}" sortBy="#{item.utilisateur}">
                                <f:facet name="header">
                                    <h:outputText value="Utilisateur"/>
                                </f:facet>
                                <h:outputText value="#{item.utilisateur.nom}"/>
                            </p:column>
                            <p:column width="300" filterBy="#{item.confidentialite}" sortBy="#{item.confidentialite}">
                                <f:facet name="header">
                                    <h:outputText value="Confidentialite"/>
                                </f:facet>
                                <h:outputText value="#{item.confidentialite.libelle}"/>
                            </p:column>
                            <p:column width="300" filterBy="#{item.etat}" sortBy="#{item.etat}">
                                <f:facet name="header">
                                    <h:outputText value="Etat"/>
                                </f:facet>
                                <h:outputText value="#{item.etat}"/>
                            </p:column>
                            <p:column width="10">
                                <f:facet name="header">
                                  <h:outputText value="Opérations"/>
                                </f:facet>
                                <p:commandLink action="#{question.supprimerQuestion(item)}">
                                    <p:confirm 
                                        header="Confirmation"
                                        message="Voulez-vous vraiment supprimer?" />
                                    <h:graphicImage name="images/del.png"/>
                                </p:commandLink>
                                <br/>
                                
                            </p:column>
                        </p:dataTable>
                        <p:confirmDialog global="true">
                          <p:commandButton value="Oui" type="button" 
                                           styleClass="ui-confirmdialog-yes"/>
                          <p:commandButton value="Non" type="button" 
                                           styleClass="ui-confirmdialog-no"/>
                        </p:confirmDialog>
                    </h:form>
                </f:view>
            </ui:define>
        </ui:composition>
    </h:body>
</html>